[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
ffi = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[soldeer]
# whether soldeer manages remappings
remappings_generate = true

# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false

# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"

# Install all subdependencies
recursive_deps = true

[dependencies]
forge-std = "foundry-rs/forge-std~v1.9.7"
flare-periphery = "flare-foundation/flare-foundry-periphery-package~80cdd9354ddcda17d3180c67c0347ba233435181"
"@openzeppelin-contracts" = "OpenZeppelin/openzeppelin-contracts~v5.4.0-rc.1"
"@openzeppelin-contracts-upgradeable" = "OpenZeppelin/openzeppelin-contracts-upgradeable~v5.4.0-rc.1"
"@prb-math" = "PaulRBerg/prb-math~v4.1.0"
smartcontractkit-chainlink = "smartcontractkit/chainlink~v2.24.0"
hedera-smart-contracts = "hashgraph/hedera-smart-contracts~v0.11.0"
hedera-forking = "hashgraph/hedera-forking~v0.1.2"
